#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 165
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 1
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 21

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_let = 6,
  anon_sym_EQ = 7,
  anon_sym_enum = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_union = 11,
  anon_sym_struct = 12,
  anon_sym_COLON = 13,
  anon_sym_int = 14,
  anon_sym_string = 15,
  anon_sym_bool = 16,
  anon_sym_LT = 17,
  anon_sym_GT = 18,
  anon_sym_return = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_PLUS = 22,
  anon_sym_DASH = 23,
  sym_number = 24,
  sym_string = 25,
  anon_sym_true = 26,
  anon_sym_false = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__declaration = 30,
  sym_function_definition = 31,
  sym_parameter_list = 32,
  sym_parameter = 33,
  sym_let_statement = 34,
  sym_enum_definition = 35,
  sym_enum_body = 36,
  sym_enum_member = 37,
  sym_union_definition = 38,
  sym_union_body = 39,
  sym_union_field = 40,
  sym_struct_definition = 41,
  sym_struct_body = 42,
  sym_struct_field = 43,
  sym__type = 44,
  sym_property_identifier = 45,
  sym_generic_type = 46,
  sym_type_literal = 47,
  sym_type_identifier = 48,
  sym_type_parameters = 49,
  sym_type_parameter = 50,
  sym_block = 51,
  sym__statement = 52,
  sym_return_statement = 53,
  sym__expression = 54,
  sym_binary_expression = 55,
  sym_primary_expression = 56,
  sym_parenthesized_expression = 57,
  sym_struct_expression = 58,
  sym_field_initilizer_list = 59,
  sym_field_initializer = 60,
  sym_call_expression = 61,
  sym_labeled_function_argument = 62,
  sym_labeled_function_argument_punned = 63,
  sym_boolean = 64,
  aux_sym_source_file_repeat1 = 65,
  aux_sym_parameter_list_repeat1 = 66,
  aux_sym_enum_body_repeat1 = 67,
  aux_sym_union_body_repeat1 = 68,
  aux_sym_struct_body_repeat1 = 69,
  aux_sym_type_parameters_repeat1 = 70,
  aux_sym_block_repeat1 = 71,
  aux_sym_field_initilizer_list_repeat1 = 72,
  aux_sym_call_expression_repeat1 = 73,
  alias_sym_struct_type = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_enum] = "enum",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_union] = "union",
  [anon_sym_struct] = "struct",
  [anon_sym_COLON] = ":",
  [anon_sym_int] = "int",
  [anon_sym_string] = "string",
  [anon_sym_bool] = "bool",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_return] = "return",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_let_statement] = "let_statement",
  [sym_enum_definition] = "enum_definition",
  [sym_enum_body] = "enum_body",
  [sym_enum_member] = "enum_member",
  [sym_union_definition] = "union_definition",
  [sym_union_body] = "union_body",
  [sym_union_field] = "union_field",
  [sym_struct_definition] = "struct_definition",
  [sym_struct_body] = "struct_body",
  [sym_struct_field] = "struct_field",
  [sym__type] = "_type",
  [sym_property_identifier] = "property_identifier",
  [sym_generic_type] = "generic_type",
  [sym_type_literal] = "type_literal",
  [sym_type_identifier] = "type_identifier",
  [sym_type_parameters] = "type_parameters",
  [sym_type_parameter] = "type_parameter",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_struct_expression] = "struct_expression",
  [sym_field_initilizer_list] = "field_initilizer_list",
  [sym_field_initializer] = "field_initializer",
  [sym_call_expression] = "call_expression",
  [sym_labeled_function_argument] = "labeled_function_argument",
  [sym_labeled_function_argument_punned] = "labeled_function_argument_punned",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_enum_body_repeat1] = "enum_body_repeat1",
  [aux_sym_union_body_repeat1] = "union_body_repeat1",
  [aux_sym_struct_body_repeat1] = "struct_body_repeat1",
  [aux_sym_type_parameters_repeat1] = "type_parameters_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_field_initilizer_list_repeat1] = "field_initilizer_list_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
  [alias_sym_struct_type] = "struct_type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_union] = anon_sym_union,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_let_statement] = sym_let_statement,
  [sym_enum_definition] = sym_enum_definition,
  [sym_enum_body] = sym_enum_body,
  [sym_enum_member] = sym_enum_member,
  [sym_union_definition] = sym_union_definition,
  [sym_union_body] = sym_union_body,
  [sym_union_field] = sym_union_field,
  [sym_struct_definition] = sym_struct_definition,
  [sym_struct_body] = sym_struct_body,
  [sym_struct_field] = sym_struct_field,
  [sym__type] = sym__type,
  [sym_property_identifier] = sym_property_identifier,
  [sym_generic_type] = sym_generic_type,
  [sym_type_literal] = sym_type_literal,
  [sym_type_identifier] = sym_type_identifier,
  [sym_type_parameters] = sym_type_parameters,
  [sym_type_parameter] = sym_type_parameter,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_struct_expression] = sym_struct_expression,
  [sym_field_initilizer_list] = sym_field_initilizer_list,
  [sym_field_initializer] = sym_field_initializer,
  [sym_call_expression] = sym_call_expression,
  [sym_labeled_function_argument] = sym_labeled_function_argument,
  [sym_labeled_function_argument_punned] = sym_labeled_function_argument_punned,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_enum_body_repeat1] = aux_sym_enum_body_repeat1,
  [aux_sym_union_body_repeat1] = aux_sym_union_body_repeat1,
  [aux_sym_struct_body_repeat1] = aux_sym_struct_body_repeat1,
  [aux_sym_type_parameters_repeat1] = aux_sym_type_parameters_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_field_initilizer_list_repeat1] = aux_sym_field_initilizer_list_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
  [alias_sym_struct_type] = alias_sym_struct_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_union] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_body] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_member] = {
    .visible = true,
    .named = true,
  },
  [sym_union_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_union_body] = {
    .visible = true,
    .named = true,
  },
  [sym_union_field] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_body] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_field_initilizer_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_labeled_function_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_labeled_function_argument_punned] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_initilizer_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_struct_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_label = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_parameters = 6,
  field_return_type = 7,
  field_right = 8,
  field_type = 9,
  field_type_parameters = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_label] = "label",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
  [field_type_parameters] = "type_parameters",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 3},
  [11] = {.index = 18, .length = 4},
  [12] = {.index = 22, .length = 3},
  [13] = {.index = 25, .length = 2},
  [14] = {.index = 27, .length = 4},
  [15] = {.index = 31, .length = 4},
  [16] = {.index = 35, .length = 3},
  [17] = {.index = 38, .length = 2},
  [18] = {.index = 40, .length = 1},
  [19] = {.index = 41, .length = 1},
  [20] = {.index = 42, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_body, 2},
    {field_name, 1},
  [3] =
    {field_type_parameters, 0},
    {field_type_parameters, 1},
  [5] =
    {field_name, 0},
  [6] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [9] =
    {field_name, 1},
    {field_value, 3},
  [11] =
    {field_body, 3},
    {field_name, 1},
  [13] =
    {field_name, 0},
    {field_type, 1},
  [15] =
    {field_type_parameters, 0},
    {field_type_parameters, 1},
    {field_type_parameters, 2},
  [18] =
    {field_body, 4},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 3},
  [22] =
    {field_body, 4},
    {field_name, 1},
    {field_parameters, 3},
  [25] =
    {field_body, 1},
    {field_name, 0},
  [27] =
    {field_type_parameters, 0},
    {field_type_parameters, 1},
    {field_type_parameters, 2},
    {field_type_parameters, 3},
  [31] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 3},
    {field_return_type, 4},
  [35] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [38] =
    {field_name, 0},
    {field_type, 2},
  [40] =
    {field_label, 1},
  [41] =
    {field_label, 0},
  [42] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [0] = alias_sym_struct_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_struct_body, 2,
    sym_struct_body,
    alias_sym_struct_type,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        '(', 6,
        ')', 8,
        '*', 15,
        '+', 17,
        ',', 7,
        '-', 18,
        '/', 16,
        ':', 12,
        '<', 13,
        '=', 9,
        '>', 14,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'e', 2,
        'f', 3,
        'i', 4,
        'l', 5,
        'r', 6,
        's', 7,
        't', 8,
        'u', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_union);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_union] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(154),
    [sym__declaration] = STATE(30),
    [sym_function_definition] = STATE(30),
    [sym_let_statement] = STATE(30),
    [sym_enum_definition] = STATE(30),
    [sym_union_definition] = STATE(30),
    [sym_struct_definition] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_union] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      sym_field_initilizer_list,
    STATE(151), 1,
      sym_type_parameters,
    ACTIONS(17), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [37] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 1,
      anon_sym_COLON,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(98), 2,
      sym_labeled_function_argument,
      sym_labeled_function_argument_punned,
    STATE(48), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [82] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_COLON,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(140), 2,
      sym_labeled_function_argument,
      sym_labeled_function_argument_punned,
    STATE(69), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [124] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_COLON,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(140), 2,
      sym_labeled_function_argument,
      sym_labeled_function_argument_punned,
    STATE(69), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [166] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 2,
      anon_sym_let,
      anon_sym_return,
    STATE(46), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [205] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_COLON,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(140), 2,
      sym_labeled_function_argument,
      sym_labeled_function_argument_punned,
    STATE(69), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    ACTIONS(17), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [266] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [298] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(74), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_SLASH,
    ACTIONS(51), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    ACTIONS(55), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [374] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [406] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [438] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(60), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_SLASH,
    ACTIONS(59), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [492] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    ACTIONS(63), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_SLASH,
    ACTIONS(67), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [536] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [558] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [590] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(63), 12,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_PLUS,
      anon_sym_DASH,
  [614] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    ACTIONS(79), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [636] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      sym_parenthesized_expression,
    STATE(131), 1,
      sym_generic_type,
    ACTIONS(37), 2,
      sym_number,
      sym_string,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(70), 6,
      sym__expression,
      sym_binary_expression,
      sym_primary_expression,
      sym_struct_expression,
      sym_call_expression,
      sym_boolean,
  [668] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(83), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [690] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_SLASH,
    ACTIONS(87), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(91), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [734] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(95), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    ACTIONS(99), 13,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [778] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      anon_sym_fn,
    ACTIONS(108), 1,
      anon_sym_let,
    ACTIONS(111), 1,
      anon_sym_enum,
    ACTIONS(114), 1,
      anon_sym_union,
    ACTIONS(117), 1,
      anon_sym_struct,
    STATE(29), 7,
      sym__declaration,
      sym_function_definition,
      sym_let_statement,
      sym_enum_definition,
      sym_union_definition,
      sym_struct_definition,
      aux_sym_source_file_repeat1,
  [809] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_union,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    STATE(29), 7,
      sym__declaration,
      sym_function_definition,
      sym_let_statement,
      sym_enum_definition,
      sym_union_definition,
      sym_struct_definition,
      aux_sym_source_file_repeat1,
  [840] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_SLASH,
    ACTIONS(122), 1,
      anon_sym_COLON,
    STATE(12), 1,
      sym_field_initilizer_list,
    STATE(151), 1,
      sym_type_parameters,
    ACTIONS(17), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
  [872] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(124), 8,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
      anon_sym_return,
  [896] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_identifier,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_let,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_return,
    STATE(90), 1,
      sym_struct_field,
    STATE(45), 4,
      sym_let_statement,
      sym__statement,
      sym_return_statement,
      aux_sym_block_repeat1,
  [924] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_block,
    STATE(80), 1,
      sym_struct_body,
    ACTIONS(142), 3,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
    STATE(123), 3,
      sym__type,
      sym_type_literal,
      sym_type_identifier,
  [950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 10,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
  [966] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block,
    STATE(80), 1,
      sym_struct_body,
    ACTIONS(142), 3,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
    STATE(141), 3,
      sym__type,
      sym_type_literal,
      sym_type_identifier,
  [992] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 10,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 10,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
  [1024] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_struct_body,
    ACTIONS(142), 3,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
    STATE(121), 3,
      sym__type,
      sym_type_literal,
      sym_type_identifier,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 9,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_RBRACE,
      anon_sym_union,
      anon_sym_struct,
  [1062] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_struct_body,
    ACTIONS(142), 3,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
    STATE(149), 3,
      sym__type,
      sym_type_literal,
      sym_type_identifier,
  [1085] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_struct_body,
    ACTIONS(142), 3,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
    STATE(127), 3,
      sym__type,
      sym_type_literal,
      sym_type_identifier,
  [1108] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_return,
    STATE(45), 4,
      sym_let_statement,
      sym__statement,
      sym_return_statement,
      aux_sym_block_repeat1,
  [1127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1142] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(156), 1,
      anon_sym_return,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(47), 4,
      sym_let_statement,
      sym__statement,
      sym_return_statement,
      aux_sym_block_repeat1,
  [1161] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 3,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_return,
  [1180] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_let,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    ACTIONS(169), 1,
      anon_sym_return,
    STATE(47), 4,
      sym_let_statement,
      sym__statement,
      sym_return_statement,
      aux_sym_block_repeat1,
  [1199] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1222] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1324] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1360] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(196), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1474] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(214), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1492] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 6,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_let,
      anon_sym_enum,
      anon_sym_union,
      anon_sym_struct,
  [1522] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
      sym_identifier,
  [1535] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      sym_enum_member,
    STATE(108), 1,
      sym_property_identifier,
  [1554] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    ACTIONS(126), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
      sym_identifier,
  [1584] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_bool,
      sym_identifier,
  [1597] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_struct_body,
    STATE(145), 1,
      sym_type_parameters,
  [1613] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    STATE(108), 1,
      sym_property_identifier,
    STATE(144), 1,
      sym_enum_member,
  [1629] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(242), 1,
      anon_sym_LPAREN,
    STATE(36), 1,
      sym_parameter_list,
    STATE(142), 1,
      sym_type_parameters,
  [1645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1655] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_union_body,
    STATE(139), 1,
      sym_type_parameters,
  [1671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1681] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_field_initializer,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1707] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RBRACE,
    STATE(115), 1,
      sym_union_field,
  [1723] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      sym_struct_field,
  [1739] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    STATE(108), 1,
      sym_property_identifier,
    STATE(144), 1,
      sym_enum_member,
  [1755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_identifier,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_parameter,
  [1768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(104), 1,
      aux_sym_union_body_repeat1,
  [1781] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      aux_sym_struct_body_repeat1,
  [1794] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(282), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      sym_struct_field,
  [1807] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RBRACE,
    ACTIONS(284), 1,
      anon_sym_COMMA,
    STATE(107), 1,
      aux_sym_struct_body_repeat1,
  [1820] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
  [1833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_GT,
    STATE(94), 1,
      aux_sym_type_parameters_repeat1,
  [1846] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
  [1859] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      aux_sym_parameter_list_repeat1,
  [1872] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_GT,
    STATE(94), 1,
      aux_sym_type_parameters_repeat1,
  [1885] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(109), 1,
      aux_sym_call_expression_repeat1,
  [1898] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_identifier,
    ACTIONS(308), 1,
      anon_sym_GT,
    STATE(110), 1,
      sym_type_parameter,
  [1911] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(112), 1,
      aux_sym_field_initilizer_list_repeat1,
  [1924] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    STATE(101), 1,
      aux_sym_enum_body_repeat1,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 3,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RBRACE,
  [1946] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    ACTIONS(321), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      sym_union_field,
  [1959] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
    STATE(104), 1,
      aux_sym_union_body_repeat1,
  [1972] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_COMMA,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
    STATE(116), 1,
      aux_sym_enum_body_repeat1,
  [1985] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(332), 1,
      anon_sym_RBRACE,
    STATE(128), 1,
      sym_struct_field,
  [1998] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      aux_sym_struct_body_repeat1,
  [2011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_EQ,
    ACTIONS(339), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2022] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_RPAREN,
    ACTIONS(343), 1,
      anon_sym_COMMA,
    STATE(117), 1,
      aux_sym_call_expression_repeat1,
  [2035] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_GT,
    STATE(97), 1,
      aux_sym_type_parameters_repeat1,
  [2048] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    STATE(143), 1,
      sym_field_initializer,
  [2061] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_RBRACE,
    ACTIONS(349), 1,
      anon_sym_COMMA,
    STATE(119), 1,
      aux_sym_field_initilizer_list_repeat1,
  [2074] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(108), 1,
      sym_property_identifier,
    STATE(144), 1,
      sym_enum_member,
  [2087] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_LPAREN,
    ACTIONS(353), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2098] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_COMMA,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_union_body_repeat1,
  [2111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    ACTIONS(359), 1,
      anon_sym_COMMA,
    STATE(101), 1,
      aux_sym_enum_body_repeat1,
  [2124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(361), 1,
      anon_sym_COMMA,
    STATE(117), 1,
      aux_sym_call_expression_repeat1,
  [2137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(364), 1,
      anon_sym_RBRACE,
    STATE(143), 1,
      sym_field_initializer,
  [2150] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      anon_sym_COMMA,
    ACTIONS(369), 1,
      anon_sym_RBRACE,
    STATE(119), 1,
      aux_sym_field_initilizer_list_repeat1,
  [2163] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(124), 1,
      sym_union_field,
  [2176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2184] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [2192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_block,
  [2202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_identifier,
    STATE(130), 1,
      sym_type_parameter,
  [2220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_field_initilizer_list,
  [2270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [2278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2294] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_enum_body,
  [2304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
    STATE(124), 1,
      sym_union_field,
  [2314] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    STATE(128), 1,
      sym_struct_field,
  [2324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_identifier,
    STATE(133), 1,
      sym_parameter,
  [2334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_union_body,
  [2344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_block,
  [2362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_parameter_list,
  [2372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2380] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_struct_body,
  [2398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_identifier,
    STATE(143), 1,
      sym_field_initializer,
  [2416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
  [2423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_RPAREN,
  [2430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
  [2437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_LBRACE,
  [2444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      sym_identifier,
  [2451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      sym_identifier,
  [2458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      ts_builtin_sym_end,
  [2465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_EQ,
  [2472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
  [2479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      sym_identifier,
  [2486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      sym_identifier,
  [2493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
  [2500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      sym_identifier,
  [2507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      sym_identifier,
  [2514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_COLON,
  [2521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
  [2528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 124,
  [SMALL_STATE(6)] = 166,
  [SMALL_STATE(7)] = 205,
  [SMALL_STATE(8)] = 244,
  [SMALL_STATE(9)] = 266,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 330,
  [SMALL_STATE(12)] = 352,
  [SMALL_STATE(13)] = 374,
  [SMALL_STATE(14)] = 406,
  [SMALL_STATE(15)] = 438,
  [SMALL_STATE(16)] = 470,
  [SMALL_STATE(17)] = 492,
  [SMALL_STATE(18)] = 514,
  [SMALL_STATE(19)] = 536,
  [SMALL_STATE(20)] = 558,
  [SMALL_STATE(21)] = 590,
  [SMALL_STATE(22)] = 614,
  [SMALL_STATE(23)] = 636,
  [SMALL_STATE(24)] = 668,
  [SMALL_STATE(25)] = 690,
  [SMALL_STATE(26)] = 712,
  [SMALL_STATE(27)] = 734,
  [SMALL_STATE(28)] = 756,
  [SMALL_STATE(29)] = 778,
  [SMALL_STATE(30)] = 809,
  [SMALL_STATE(31)] = 840,
  [SMALL_STATE(32)] = 872,
  [SMALL_STATE(33)] = 896,
  [SMALL_STATE(34)] = 924,
  [SMALL_STATE(35)] = 950,
  [SMALL_STATE(36)] = 966,
  [SMALL_STATE(37)] = 992,
  [SMALL_STATE(38)] = 1008,
  [SMALL_STATE(39)] = 1024,
  [SMALL_STATE(40)] = 1047,
  [SMALL_STATE(41)] = 1062,
  [SMALL_STATE(42)] = 1085,
  [SMALL_STATE(43)] = 1108,
  [SMALL_STATE(44)] = 1127,
  [SMALL_STATE(45)] = 1142,
  [SMALL_STATE(46)] = 1161,
  [SMALL_STATE(47)] = 1180,
  [SMALL_STATE(48)] = 1199,
  [SMALL_STATE(49)] = 1222,
  [SMALL_STATE(50)] = 1240,
  [SMALL_STATE(51)] = 1252,
  [SMALL_STATE(52)] = 1264,
  [SMALL_STATE(53)] = 1276,
  [SMALL_STATE(54)] = 1288,
  [SMALL_STATE(55)] = 1300,
  [SMALL_STATE(56)] = 1312,
  [SMALL_STATE(57)] = 1324,
  [SMALL_STATE(58)] = 1336,
  [SMALL_STATE(59)] = 1348,
  [SMALL_STATE(60)] = 1360,
  [SMALL_STATE(61)] = 1378,
  [SMALL_STATE(62)] = 1390,
  [SMALL_STATE(63)] = 1402,
  [SMALL_STATE(64)] = 1414,
  [SMALL_STATE(65)] = 1426,
  [SMALL_STATE(66)] = 1438,
  [SMALL_STATE(67)] = 1450,
  [SMALL_STATE(68)] = 1462,
  [SMALL_STATE(69)] = 1474,
  [SMALL_STATE(70)] = 1492,
  [SMALL_STATE(71)] = 1510,
  [SMALL_STATE(72)] = 1522,
  [SMALL_STATE(73)] = 1535,
  [SMALL_STATE(74)] = 1554,
  [SMALL_STATE(75)] = 1571,
  [SMALL_STATE(76)] = 1584,
  [SMALL_STATE(77)] = 1597,
  [SMALL_STATE(78)] = 1613,
  [SMALL_STATE(79)] = 1629,
  [SMALL_STATE(80)] = 1645,
  [SMALL_STATE(81)] = 1655,
  [SMALL_STATE(82)] = 1671,
  [SMALL_STATE(83)] = 1681,
  [SMALL_STATE(84)] = 1697,
  [SMALL_STATE(85)] = 1707,
  [SMALL_STATE(86)] = 1723,
  [SMALL_STATE(87)] = 1739,
  [SMALL_STATE(88)] = 1755,
  [SMALL_STATE(89)] = 1768,
  [SMALL_STATE(90)] = 1781,
  [SMALL_STATE(91)] = 1794,
  [SMALL_STATE(92)] = 1807,
  [SMALL_STATE(93)] = 1820,
  [SMALL_STATE(94)] = 1833,
  [SMALL_STATE(95)] = 1846,
  [SMALL_STATE(96)] = 1859,
  [SMALL_STATE(97)] = 1872,
  [SMALL_STATE(98)] = 1885,
  [SMALL_STATE(99)] = 1898,
  [SMALL_STATE(100)] = 1911,
  [SMALL_STATE(101)] = 1924,
  [SMALL_STATE(102)] = 1937,
  [SMALL_STATE(103)] = 1946,
  [SMALL_STATE(104)] = 1959,
  [SMALL_STATE(105)] = 1972,
  [SMALL_STATE(106)] = 1985,
  [SMALL_STATE(107)] = 1998,
  [SMALL_STATE(108)] = 2011,
  [SMALL_STATE(109)] = 2022,
  [SMALL_STATE(110)] = 2035,
  [SMALL_STATE(111)] = 2048,
  [SMALL_STATE(112)] = 2061,
  [SMALL_STATE(113)] = 2074,
  [SMALL_STATE(114)] = 2087,
  [SMALL_STATE(115)] = 2098,
  [SMALL_STATE(116)] = 2111,
  [SMALL_STATE(117)] = 2124,
  [SMALL_STATE(118)] = 2137,
  [SMALL_STATE(119)] = 2150,
  [SMALL_STATE(120)] = 2163,
  [SMALL_STATE(121)] = 2176,
  [SMALL_STATE(122)] = 2184,
  [SMALL_STATE(123)] = 2192,
  [SMALL_STATE(124)] = 2202,
  [SMALL_STATE(125)] = 2210,
  [SMALL_STATE(126)] = 2220,
  [SMALL_STATE(127)] = 2228,
  [SMALL_STATE(128)] = 2236,
  [SMALL_STATE(129)] = 2244,
  [SMALL_STATE(130)] = 2252,
  [SMALL_STATE(131)] = 2260,
  [SMALL_STATE(132)] = 2270,
  [SMALL_STATE(133)] = 2278,
  [SMALL_STATE(134)] = 2286,
  [SMALL_STATE(135)] = 2294,
  [SMALL_STATE(136)] = 2304,
  [SMALL_STATE(137)] = 2314,
  [SMALL_STATE(138)] = 2324,
  [SMALL_STATE(139)] = 2334,
  [SMALL_STATE(140)] = 2344,
  [SMALL_STATE(141)] = 2352,
  [SMALL_STATE(142)] = 2362,
  [SMALL_STATE(143)] = 2372,
  [SMALL_STATE(144)] = 2380,
  [SMALL_STATE(145)] = 2388,
  [SMALL_STATE(146)] = 2398,
  [SMALL_STATE(147)] = 2406,
  [SMALL_STATE(148)] = 2416,
  [SMALL_STATE(149)] = 2423,
  [SMALL_STATE(150)] = 2430,
  [SMALL_STATE(151)] = 2437,
  [SMALL_STATE(152)] = 2444,
  [SMALL_STATE(153)] = 2451,
  [SMALL_STATE(154)] = 2458,
  [SMALL_STATE(155)] = 2465,
  [SMALL_STATE(156)] = 2472,
  [SMALL_STATE(157)] = 2479,
  [SMALL_STATE(158)] = 2486,
  [SMALL_STATE(159)] = 2493,
  [SMALL_STATE(160)] = 2500,
  [SMALL_STATE(161)] = 2507,
  [SMALL_STATE(162)] = 2514,
  [SMALL_STATE(163)] = 2521,
  [SMALL_STATE(164)] = 2528,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_expression, 2, 0, 13),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_expression, 2, 0, 13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 16),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 16),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 4),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_initilizer_list, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_initilizer_list, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5, 0, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 5, 0, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_initilizer_list, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_initilizer_list, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_initilizer_list, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_initilizer_list, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 6, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 6, 0, 4),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_initilizer_list, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_initilizer_list, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(160),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(158),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(152),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(157),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(153),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4, 0, 7),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(162),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(158),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 5, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_body, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(158),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_labeled_function_argument, 3, 0, 19),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 3, 0, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 6),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 4, 0, 8),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 12),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 3, 0, 4),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 4, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 3, 0, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 3, 0, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_body, 5, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 5, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_body, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 4, 0, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_initializer, 3, 0, 20),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 15),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 5),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_literal, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(138),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [291] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_parameters_repeat1, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [314] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_body_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_body_repeat1, 2, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_identifier, 1, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_body_repeat1, 2, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [334] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_body_repeat1, 2, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 1, 0, 4),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 1, 0, 4),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [361] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [366] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_initilizer_list_repeat1, 2, 0, 0), SHIFT_REPEAT(147),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_initilizer_list_repeat1, 2, 0, 0),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 9),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 2, 0, 3),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 3, 0, 10),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 17),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_labeled_function_argument_punned, 2, 0, 18),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameters, 4, 0, 14),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_field, 4, 0, 17),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 1, 0, 4),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, 0, 4),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [399] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gloss(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
